apiVersion: v1
kind: Service
metadata:
  name: cp-ksql-server
  namespace: ${{ env.NAMESPACE }}
  labels:
    app: cp-ksql-server
spec:
  ports:
      - name: "8088"
        port: 8088
        targetPort: 8088
  selector:
    app: cp-ksql-server
