name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CLUSTER_NAME: DiAmuz
  CLUSTER_RESOURCE_GROUP: development
  NAMESPACE: ksqldb
  
jobs:

  deploy:
    
    # Set the target Azure Kubernetes Service (AKS) cluster. 
    steps:
    - uses: actions/checkout@master
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    
    # Create namespace if doesn't exist
    - run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -
    
    # Deploy app to AKS
    - uses: azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/ksql-aks-deployment.yml
          manifests/ksql-aks-svc.yml
        namespace: ${{ env.NAMESPACE }}
